  version: "3.8"
  services:
    postgres:
      build:
        context: services/postgres
        dockerfile: Dockerfile
      ports:
        - "5433:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=product_monitoring
        - POSTGRES_PASSWORD=postgres
      volumes:
        - "db-data:/var/lib/postgresql/data"


    app:
      build:
        context: services/app
        dockerfile: Dockerfile
      environment:
        - PORT=8080
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/product_monitoring
      image: 'my-java'
      ports:
        - "8091:8080"
      depends_on:
        - postgres

  volumes:
    db-data: