-- table: user
create table "user"
(
    id         integer generated by default as identity
        constraint user_pkey
            primary key,
    first_name varchar(25),
    last_name  varchar(25),
    password   varchar(255) not null,
    username   varchar(20)  not null
        constraint user_username_key
            unique,
    email      varchar(30)  not null
        constraint user_email_key
            unique
);


-- table: role
create table role
(
    id        integer generated by default as identity
        constraint role_pkey
            primary key,
    role_type varchar(20) not null
);


-- table for mapping user and role
create table user_role
(
    user_id integer not null
        constraint user_role_user_id_fk
            references "user"
            on update cascade,
    role_id integer not null
        constraint user_role_role_id_fk
            references role
            on update cascade,
    unique (user_id, role_id)
);


-- table: product
create table product
(
    id           integer generated by default as identity
        constraint product_pkey
            primary key,
    product_name varchar(30) not null
        constraint product_product_name_key
            unique
);


-- table: category
create table category
(
    id            integer generated by default as identity
        constraint category_pkey
            primary key,
    category_name varchar(30) not null
        constraint category_category_name_key
            unique
);


-- table for mapping product and category
create table category_product
(
    category_id integer not null
        constraint category_product_category_id_fk
            references category
            on update cascade,
    product_id  integer not null
        constraint category_product_product_id_fk
            references product
            on update cascade
        unique (category_id, product_id)
);


-- table: store
create table store
(
    id         integer generated by default as identity
        constraint store_pkey
            primary key,
    store_name varchar(100) not null
);


-- table: price
create table price
(
    id         integer generated by default as identity
        constraint price_pkey
            primary key,
    unit_price integer   not null,
    date       timestamp not null,
    product_id integer   not null
        constraint price_product_id_fk
            references product
            on update cascade,
    store_id   integer   not null
        constraint price_store_id_fk
            references store
            on update cascade
);